CarSaleSix/Models/CUSTOMER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CarSaleSix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
       
        [Key]
        public int CUSTID { get; set; }

        [Display(Name = "First Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required")]
        [DataType(DataType.Text)]
        public string FIRST { get; set; }


        [Display(Name = "Last Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is required")]
        [DataType(DataType.Text)]
        public string LAST { get; set; }


        [Display(Name = "Email Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email Address is required")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }


        [Display(Name = "Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [MinLength(8,ErrorMessage = "Password needs to be minimum 8 characters")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Confirm Password is required")]
        [Compare("PASSWORD",ErrorMessage = "Confirm Password does not match")]
        [DataType(DataType.Password)]
        public string CONFIRMPASSWORD { get; set; }

        [Display(Name = "Phone Number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone Number is required")]
        [DataType(DataType.PhoneNumber)]
        public string PHONE { get; set; }

        [Display(Name = "Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Address is required")]
        [DataType(DataType.Text)]
        public string ADDRESS { get; set; }

        public bool ISEMAILVERIFIED { get; set; }
        public System.Guid ACTIVATIONCODE { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}

CarSaleSix/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarSaleSix.Models
{
    public class Login
    {
        [Display(Name = "Email Address")]
        [Required(AllowEmptyStrings = false , ErrorMessage = "Email ID is required")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        public string PASSWORD { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }


    }
}

CarSaleSix/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarSaleSix.Models;

namespace CarSaleSix.Controllers
{
    public class BillsController : Controller
    {
        private CarsEntities db = new CarsEntities();

        // GET: Bills
        public ActionResult Index()
        {
            return View(db.BILLS.ToList());
        }

        // GET: Bills/Details/
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bill = db.BILLS.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BILL bill)
        {
            bool Status = false;
            string Message = "";
            if (ModelState.IsValid)
            {
                db.BILLS.Add(bill);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.Message = Message;
            ViewBag.Status = Status;
            return View(bill);
        }

        // GET: Bills/Edit/
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bill = db.BILLS.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BILL bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bill);
        }

        // GET: Bills/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BILL bILL = db.BILLS.Find(id);
            if (bILL == null)
            {
                return HttpNotFound();
            }
            return View(bILL);
        }

        // POST: Bills/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BILL bILL = db.BILLS.Find(id);
            db.BILLS.Remove(bILL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarSaleSix/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CarSaleSix.Models;

namespace CarSaleSix.Controllers
{
    public class CustomerController : Controller
    {
        private CarsEntities db = new CarsEntities();

        // GET: CUSTOMERs
        public ActionResult Index()
        {
            return View(db.CUSTOMERS.ToList());
        }

        // GET: CUSTOMERs/Details/
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CUSTOMER customer = db.CUSTOMERS.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

        // GET: CUSTOMERs/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CUSTOMERs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "ISEMAILVERIFIED,ACTIVATIONCODE")]CUSTOMER customer)
        {
            bool Status = false;
            string Message = "";
            if (ModelState.IsValid)
            {


                #region Email Already Exists

                var isExist = IsEmailExist(customer.EMAIL);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExists","Email Already Exists");
                    return View(customer);
                }

                #endregion

                #region Generate Activation Code

                customer.ACTIVATIONCODE = Guid.NewGuid();

                #endregion

                #region Password Hashing

                customer.PASSWORD = Crypto.Hash(customer.PASSWORD);
                customer.CONFIRMPASSWORD = Crypto.Hash(customer.CONFIRMPASSWORD);

                #endregion

                customer.ISEMAILVERIFIED = false;

                #region Save to Database

                {
                    db.CUSTOMERS.Add(customer);
                    db.SaveChanges();

                    #region Send Email Verification link to User

                    SendVerificationLinkEmail(customer.EMAIL, customer.ACTIVATIONCODE.ToString());
                    Message =
                        "Registration Successfully Done. Account link activation link has been sent to your email id: " +
                        customer.EMAIL;
                    Status = true;
                    #endregion
                }

                #endregion

                //return RedirectToAction("Index");
            }
            else
            {
                Message = "Invalid Request";
            }

            ViewBag.Message = Message;
            ViewBag.Status = Status;

            return View(customer);
        }


        [NonAction]
        private bool IsEmailExist(string email)
        {
            var c = db.CUSTOMERS.FirstOrDefault(a => a.EMAIL == email);
            return c != null;
        }

        [NonAction]
        public void SendVerificationLinkEmail(string emailID, string activationCode, string emailFor="VerifyAccount")
        {
            var verifyUrl = "/Customer/"+emailFor+"/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            var fromEmail = new MailAddress("carsalesdotnet@gmail.com", "Sales Gen 2018");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "qazwsxedcrfvtgbyhnujmikolp";
            string subject = "";
            string body = "";

            if (emailFor == "VerifyAccount")
            {
                 subject = "Your account is successfully created";
                 body =
                    "<br><br> We are excited to tell you that your Sales Gen account has been successfully created. Please click the below link to verify your account" +
                    "<br><a href='" + link + "'>" + link + "</a>";
            }else if (emailFor=="ResetPassword")
            {
                subject = "Reset Password";
                body =
                    "Hi, You requested for resetting the password of your Sales Gen account. Click on the below link to reset" +
                    "<br><br><a href=" + link + ">Reset Password</a>";
            }
           
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };
            using (var Message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })

                smtp.Send(Message);

        }


        //Verify Account
        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool s = false;
   
           
                db.Configuration.ValidateOnSaveEnabled = false; //to avoid confirm password does not match issue
                var v = db.CUSTOMERS.Where(a => a.ACTIVATIONCODE == new Guid(id)).FirstOrDefault();
                if (v != null)
                {
                    v.ISEMAILVERIFIED = true;
                    db.SaveChanges();
                    s = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }

            ViewBag.Status = s;
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login login, string ReturnUrl="")
        {
            string Message = "";
            var v = db.CUSTOMERS.FirstOrDefault(a => a.EMAIL == login.EMAIL);
            if (v != null)
            {
                if (String.CompareOrdinal(Crypto.Hash(login.PASSWORD), v.PASSWORD) == 0)
                {
                    int timeout = login.RememberMe ? 10080 : 20;
                    var ticket = new FormsAuthenticationTicket(login.EMAIL, login.RememberMe, timeout);
                    string encrypt = FormsAuthentication.Encrypt(ticket);
                    var cookie = new HttpCookie(FormsAuthentication.FormsCookieName,encrypt);
                    cookie.Expires = DateTime.Now.AddMinutes(timeout);
                    cookie.HttpOnly = true;
                    Response.Cookies.Add(cookie);
                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    Message = "Invalid Credentials";
                }
            }
            else
            {
                Message = "Invalid Credentials";
            }
            ViewBag.Message = Message;
            return View();
        }

        
        //logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage("Index");
            return RedirectToAction("Index", "Customer");
        }


        // GET: CUSTOMERs/Edit/
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CUSTOMER customer = db.CUSTOMERS.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

        // POST: CUSTOMERs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CUSTOMER customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: CUSTOMERs/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CUSTOMER customer = db.CUSTOMERS.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

        // POST: CUSTOMERs/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CUSTOMER customer = db.CUSTOMERS.Find(id);
            db.CUSTOMERS.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }

        //Forgot Password
        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string email)
        {
            //verify the email
            string Message = "";
            bool Status = false;

CarSaleSix/Views/Customer/Create.cshtml
@model CarSaleSix.Models.CUSTOMER

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron">
<h2>Register a new Customer</h2>

@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">Success @ViewBag.Message</div>
    }
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FIRST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FIRST, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FIRST, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LAST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LAST, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LAST, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                    @Html.ValidationMessage("EmailExists", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CONFIRMPASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CONFIRMPASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CONFIRMPASSWORD, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PHONE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PHONE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PHONE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ADDRESS, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">Error @ViewBag.Message</div>
        }
    }
}

<div>
    @Html.ActionLink("Login", "Login")
</div>
</div>
@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
}

CarSaleSix/Views/Customer/Delete.cshtml
@model CarSaleSix.Models.CUSTOMER

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron">
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CUSTOMER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIRST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIRST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LAST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LAST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PHONE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHONE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
    </div>

CarSaleSix/Views/Customer/Details.cshtml
@model CarSaleSix.Models.CUSTOMER

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron">
<h2>Details</h2>

<div>
    <h4>CUSTOMER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIRST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIRST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LAST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LAST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PHONE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHONE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CUSTID }) <br/>
    @Html.ActionLink("Back to List", "Index")<br/>
    @Html.ActionLink("Reset Password","ResetPassword")<br/>
    @Html.ActionLink("Add Bill","Create","Bills")
</p>
</div>

CarSaleSix/Views/Customer/Edit.cshtml
@model CarSaleSix.Models.CUSTOMER

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">Success @ViewBag.Message</div>
    }
}
else
{
    if (@Context.User.Identity.Name.ToString().ToLower() == "carsalesdotnet@gmail.com")
    {
        using (Html.BeginForm())
         {
             @Html.AntiForgeryToken()
             <div class="jumbotron">
                 <div class="form-horizontal">
                     <h4>CUSTOMER</h4>
                     <hr/>
                     @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                     @Html.HiddenFor(model => model.CUSTID)

                     <div class="form-group">
                         @Html.LabelFor(model => model.FIRST, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.FIRST, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.FIRST, "", new {@class = "text-danger"})
                         </div>
                     </div>

                     <div class="form-group">
                         @Html.LabelFor(model => model.LAST, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.LAST, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.LAST, "", new {@class = "text-danger"})
                         </div>
                     </div>

                     <div class="form-group">
                         @Html.LabelFor(model => model.EMAIL, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.EMAIL, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.EMAIL, "", new {@class = "text-danger"})
                         </div>
                     </div>

                     <div class="form-group">
                         @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.PASSWORD, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.PASSWORD, "", new {@class = "text-danger"})
                         </div>
                     </div>
                     <div class="form-group">
                         @Html.LabelFor(model => model.CONFIRMPASSWORD, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.CONFIRMPASSWORD, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.CONFIRMPASSWORD, "", new {@class = "text-danger"})
                         </div>
                     </div>
                     <div class="form-group">
                         @Html.LabelFor(model => model.PHONE, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.PHONE, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.PHONE, "", new {@class = "text-danger"})
                         </div>
                     </div>

                     <div class="form-group">
                         @Html.LabelFor(model => model.ADDRESS, htmlAttributes: new {@class = "control-label col-md-2"})
                         <div class="col-md-10">
                             @Html.EditorFor(model => model.ADDRESS, new {htmlAttributes = new {@class = "form-control"}})
                             @Html.ValidationMessageFor(model => model.ADDRESS, "", new {@class = "text-danger"})
                         </div>
                     </div>

                     <div class="form-group">
                         <div class="col-md-offset-2 col-md-10">
                             <input type="submit" value="Save" class="btn btn-default"/>
                         </div>
                     </div>
                 </div>
             </div>

             if (ViewBag.Message != null)
             {
                 <div class="alert alert-danger">Error @ViewBag.Message</div>
             }
         }
    }
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarSaleSix/Views/Customer/ForgotPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Forgot Password</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr/>
        <div class="text-success">@ViewBag.Message</div>
        <div class="form-group">
            <label class="control-label col-md-2">Email ID</label>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="submit" class="btn btn-success"/>
            </div>
        </div>
    </div>
}

CarSaleSix/Views/Customer/ResetPassword.cshtml
@model CarSaleSix.Models.ResetPasswordModel

@{
    ViewBag.Title = "ResetPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron">
<h2>Reset Password</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="text-danger">@ViewBag.Message</div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Reset" class="btn btn-default"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
    </div>